# Generated by Django 6.0.3 on 2026-03-23 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_alter_reminder_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reminder',
            name='unique_position_per_list',
        ),
    ]
