# Generated by Django 6.0.3 on 2026-03-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_remove_reminder_unique_position_per_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='colour',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('accent', 'Accent'), ('error', 'Error'), ('info', 'Info')], default='primary', max_length=12),
        ),
    ]
