# Generated by Django 6.0.3 on 2026-03-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0005_list_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='icon',
            field=models.CharField(choices=[('list', 'List'), ('bookmark', 'Bookmark'), ('key', 'Key'), ('present', 'Present')], default='list', max_length=24),
        ),
        migrations.AlterField(
            model_name='list',
            name='colour',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('info', 'Info')], default='primary', max_length=12),
        ),
    ]
