# Generated by Django 6.0.3 on 2026-03-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0006_list_icon_alter_list_colour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['name']},
        ),
    ]
